apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`alertmanager.{{.Values.domain}}`)
      kind: Rule
      services:
        - name: {{.Release.Name }}-kube-prom-alertmanager
          port: 9093