replicaCount: 1

image:
  repository: ghcr.io/investment-alert-system/investment-alert-frontend/app
  pullPolicy: IfNotPresent
  tag: "51bc158d61acdcb8f42ea0ce7f15ccb8c0c10390"

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

ingress:
  domain: localhost